### ISSUE TITLE
Unauthorized Use of API Key on lakshanrukantha.github.io

### ISSUE THREAD

**Issue by LakshanRukantha** [qaidjoharj53/Portfolio#1]
Hello Qaidjohar,

Thank you for using my portfolio as a template. However, I noticed that my API key, intended for use with my website hosted on GitHub Pages (https://lakshanrukantha.github.io/), has been used without my permission.

Please remove my API key from your repository and also ensure that you are not using my Google Analytics IDs. This will resolve the issue promptly.

Thank you.

**Comment by qaidjoharj53** [comment]
Hi @LakshanRukantha,
Upon your issue, I searched and reviewed my code but neither I found any of your API Key being used in my code nor any Google Analytics IDs.
If you have found any, please let me know the file name and the line of code.

**Comment by LakshanRukantha** [comment]
That is in the index page contact form action URL. I received some responses from your domain, indicating its usage. I utilized Formspree mail service to develop this feature. Therefore, I recommend creating an account on [Formspree](https://formspree.io/) and obtaining your unique form action URL to replace the current one in your code.

Thank you.
